name: "TF Deploy"
run-name: TF Deploy

on:
  workflow_dispatch:

jobs:
  Git-Config:
    name: git-config
    runs-on: ubuntu-latest
    steps:
      - run: git config --global url."https://oauth2:${{ secrets.PAT }}@github.com"insteadOf https://github.com

  TF-Deploy:
        name: tf-deploy
        secrets: inherit
        uses: kicka5h/github-reusable-workflows/.github/workflows/terraformm/tfdeploy.yml@main
